configuration: Release
skip_tags: true

before_build:
  - nuget restore
after_build:
  - nuget pack CreditCard/CreditCard.fsproj -symbols -properties Configuration=Release -outputdirectory ./CreditCard

artifacts:
  - path: 'CreditCard\**\*.nupkg'
    name: NuGet package
  - path: 'CreditCard\bin\Release\**\CreditCard.dll'
    name: Dynamic link library

nuget:
  account_feed: true
  project_feed: true

deploy:
  - provider: NuGet
    on:
      appveyor_repo_tag: true
    api_key:
      secure: QUWvYraR0a9U/rMnQqjYZDuo9ZTOXK9bAiwtQGw3PS67k467JI0DqZwCB6C/GUo2
    artifact: /^CreditCard(.+)\.nupkg$/

  - provider: GitHub 
    release: CreditCard-v$(appveyor_build_version)
    description: 'Release description'
    auth_token:
      secure: QVr281KEblDYeDlKbF7NOJEhHPcX8RgMNTIlCM4TGxHFcpuSZvvUi9e4F3DSgx45
    artifact: /^CreditCard(.+)\.nupkg$/
    draft: false
    prerelease: false
    on:
      appveyor_repo_tag: true
